### ISSUE TITLE
Error : species number key is duplicated 

### ISSUE THREAD

**Issue by ghost** [EDiLD/localecotox#1]
Dear Ed, I recently need to work on a project related to the EPA ecotox database. I ran through your code and encountered an error as below. After checking the file, there are indeed two Holcus cernuus in the file with number being 3895. I am not sure what to do with this now. Do you have any idead?

```
dbSendQuery(con, "ALTER TABLE species ADD PRIMARY KEY (species_number)")
# Error in postgresqlExecStatement(conn, statement, ...) : 
#   RS-DBI driver: (could not Retrieve the result : ERROR:  could not create unique index "species_synonyms_pkey"
# DETAIL:  Key (species_number, latin_name)=(3895, Holcus cernuus) is duplicated.
```

**Comment by eduardszoecs** [comment]
Ugh this is really old code here... 
Quick-fix: Don't add the primary key or add another primary key. DB will still work but performance might be slower.

**Comment by ghost** [comment]
It is old but useful still! It has make my exploring of the db easier than using the internet UI. Thank again for the quick response!
